version: '3.7'
services:

    zookeeper:
        image: 'bitnami/zookeeper:3'
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - streaming

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        networks:
            - streaming

    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        ports:
            - "5601:5601"
        networks:
            - streaming

    kafka-gateway:
        image: 'bitnami/kafka:1'
        ports:
            - 9092:9092
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CREATE_TOPICS= "rawTaxi,cookedTaxi"
        depends_on:
            - zookeeper
        networks:
            - streaming

    flink-app:
        build: ./Flink
        volumes:
            - ./data-input:/data-input
        ports:
            - 8081:8080
        environment:
            flink.prop.address: kafka-gateway:9092
        depends_on:
            - kafka-gateway
        networks:
            - streaming

    camel-app:
        build: ./Camel
        volumes:
          - ./Data:/Data
        ports:
            - 8080:8080
        environment:
            camel.component.elasticsearch-rest.client: https://docker-cluster:9200
            camel.component.elasticsearch-rest.host-addresses: elasticsearch:9200
            camel.message-producer.from: file:/Data/?noop=true&maxMessagesPerPoll=1&delay=5000
            camel.message-producer.kafka: kafka:rawTaxi?brokers=kafka-gateway:9092
            camel.message-consumer.kafka: kafka:rawTaxi?brokers=kafka-gateway:9092
            mongodb.host: mongodb-gateway
            camel.elastic.kafka: kafka:cookedTaxi?brokers=kafka-gateway:9092
        depends_on:
            - kafka-gateway
        networks:
            - streaming

    mongodb-gateway:
        container_name: mongo
        image: mongo:3.6
        volumes:
            - ./data/db:/var/micro-data/mongodb/data/db
        environment:
            - MONGODB_INITDB_DATABASE=taxi
            - MONGODB_INITDB_COLLECTION=nyc
        ports:
          - 27017:27017
        networks:
          - streaming

networks:
  streaming:
